# Blog
keywords: mq,rmq,realtime,develop,programming,ios,android,macos,linux,windows
author: DeepThought Co., Ltd.,mikimoto@deepthought.tech
description: DeepThought Co., Ltd. Offical Blog
avatar: /images/avatar.png
favicon: /imges/favicon.ico

# Social Accounts
twitter: 
facebook: "https://www.facebook.com/deepthought.tech/"
github: "https://github.com/DeepThoughtTech/"
rss: /atom.xml

# Comment
#duoshuo: 
#disqus: 
#gentie: 
